// Mocks generated by Mockito 5.0.12 from annotations
// in shopys/test/app/features/home/data/datasources/product_datasource_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shopys/app/core/http_client/http_client.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeHttpResponse extends _i1.Fake implements _i2.HttpResponse {}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.HttpResponse> get(String? url) =>
      (super.noSuchMethod(Invocation.method(#get, [url]),
              returnValue: Future<_i2.HttpResponse>.value(_FakeHttpResponse()))
          as _i3.Future<_i2.HttpResponse>);
  @override
  _i3.Future<_i2.HttpResponse> post(String? url, Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#post, [url, json]),
              returnValue: Future<_i2.HttpResponse>.value(_FakeHttpResponse()))
          as _i3.Future<_i2.HttpResponse>);
}
